### ISSUE TITLE
Can MPU6050 sensor be used instead of MPU9150?

### ISSUE THREAD

**Issue by shivambhavsar** [voroshkov/UsbMouseGlove#1]
http://www.ebay.in/itm/GY-521-MPU-6050-Module-3-Axis-Gyroscope-Accelerometer-for-Arduino-/331689339314?hash=item4d3a39a9b2

This is a sensor link. Please see its description. I want to know if this item can be used instead of GY 9150 used in http://voroshkov.blogspot.in/2014/09/usb-mouse-glove-instruction.html

**Comment by voroshkov** [comment]
Absolutely. You can use 6050 as well.

**Comment by shivambhavsar** [comment]
thankyou so much. I appreciate your work. keep it up!! :)
